version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:4.2.1
    restart: always
    ports:
      - 27017:27017
    networks:
      - database
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

networks:
  database:
    driver: bridge
