version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:4.2.1
    restart: always
    ports:
      - 27017:27017
    networks:
      - database
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/

networks:
  database:
    driver: bridge
